/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.muspellheim.portfoliosimulation.backend

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
